-- Insert sample OOH listings data
INSERT INTO ooh_listings (
  name, type, latitude, longitude, address, city, state,
  size, illumination, visibility, traffic,
  monthly_price, availability, description, images, features,
  footfall, target_audience
) VALUES 
(
  'MG Road Premium Billboard',
  'Billboard',
  12.9716, 77.5946,
  'MG Road, Near Brigade Road Junction',
  'Bangalore', 'Karnataka',
  '40ft x 20ft', 'Lit', 'High', '2.5L+ daily',
  150000, 'Available',
  'Premium billboard location on MG Road with high visibility and excellent foot traffic.',
  ARRAY['/placeholder.svg?height=300&width=400'],
  ARRAY['Prime Location', 'LED Illumination', 'Weather Resistant', '24/7 Visibility'],
  '2.5 Lakh+ daily',
  'Urban professionals, shoppers, tourists'
),
(
  'Koramangala Digital Display',
  'Digital Display',
  12.9352, 77.6245,
  '5th Block, Koramangala',
  'Bangalore', 'Karnataka',
  '20ft x 15ft', 'Digital', 'High', '1.8L+ daily',
  200000, 'Available',
  'Modern digital display in the heart of Koramangala tech hub.',
  ARRAY['/placeholder.svg?height=300&width=400'],
  ARRAY['Digital Display', 'Multiple Ad Slots', 'Remote Control', 'HD Quality'],
  '1.8 Lakh+ daily',
  'Tech professionals, young adults, students'
),
(
  'Indiranagar Metro Station',
  'Transit',
  12.9719, 77.6412,
  'Indiranagar Metro Station',
  'Bangalore', 'Karnataka',
  '12ft x 8ft', 'Lit', 'High', '3L+ daily',
  120000, 'Booked',
  'High-traffic metro station advertising space with excellent commuter visibility.',
  ARRAY['/placeholder.svg?height=300&width=400'],
  ARRAY['Metro Station', 'Commuter Traffic', 'Backlit Display', 'Weather Protected'],
  '3 Lakh+ daily',
  'Daily commuters, office workers'
),
(
  'Forum Mall Digital Screen',
  'Mall Display',
  12.9352, 77.6245,
  'Forum Mall, Koramangala',
  'Bangalore', 'Karnataka',
  '15ft x 10ft', 'Digital', 'High', '50K+ daily',
  180000, 'Available',
  'Premium digital screen inside Forum Mall with high dwell time.',
  ARRAY['/placeholder.svg?height=300&width=400'],
  ARRAY['Mall Location', 'Digital Screen', 'High Dwell Time', 'Targeted Audience'],
  '50K+ daily',
  'Shoppers, families, young adults'
),
(
  'Whitefield Tech Park Billboard',
  'Billboard',
  12.9698, 77.75,
  'ITPL Main Road, Whitefield',
  'Bangalore', 'Karnataka',
  '30ft x 15ft', 'Lit', 'High', '1.2L+ daily',
  100000, 'Available',
  'Strategic billboard targeting IT professionals in Whitefield tech corridor.',
  ARRAY['/placeholder.svg?height=300&width=400'],
  ARRAY['Tech Hub Location', 'LED Backlit', 'Professional Audience', 'High Visibility'],
  '1.2 Lakh+ daily',
  'IT professionals, tech workers'
),
(
  'Electronic City Digital Board',
  'Digital Display',
  12.8456, 77.6603,
  'Electronic City Phase 1',
  'Bangalore', 'Karnataka',
  '25ft x 15ft', 'Digital', 'High', '1.5L+ daily',
  175000, 'Available',
  'High-tech digital display targeting IT professionals in Electronic City.',
  ARRAY['/placeholder.svg?height=300&width=400'],
  ARRAY['Digital Display', 'Tech Hub Location', 'High Resolution', 'Remote Updates'],
  '1.5 Lakh+ daily',
  'IT professionals, tech workers, commuters'
),
(
  'Hebbal Flyover Billboard',
  'Billboard',
  13.0358, 77.597,
  'Hebbal Flyover, Outer Ring Road',
  'Bangalore', 'Karnataka',
  '50ft x 25ft', 'Lit', 'High', '3L+ daily',
  250000, 'Available',
  'Massive billboard on busy Hebbal flyover with excellent highway visibility.',
  ARRAY['/placeholder.svg?height=300&width=400'],
  ARRAY['Highway Location', 'Large Format', 'LED Backlit', 'High Traffic'],
  '3 Lakh+ daily',
  'Commuters, highway travelers, airport traffic'
);
